src/main/java/sim/coffee/Colour.java
src/main/java/sim/coffee/DietaryClass.java
src/main/java/sim/coffee/Label.java
src/main/java/sim/coffee/Milk.java
src/main/java/sim/coffee/Size.java

Implement Enumerated Types

---

src/main/java/sim/coffee/Order.java
src/main/java/sim/coffee/OrderItem.java
src/test/java/sim/coffee/OrderTest.java

Order class

---

src/main/java/sim/coffee/OrderItem.java

Order Item class should be working

Implement OrderItem classes

---

src/main/java/sim/coffee/Menu.java
src/main/java/sim/coffee/OrderBeverage.java
src/main/java/sim/coffee/OrderFood.java
src/main/java/sim/coffee/OrderItem.java
src/main/java/sim/coffee/OrderList.java
src/main/java/sim/coffee/OrderMerchandise.java

Initial implementation of the order list as per our UML planning
I'm opening this on behalf of @yeshwanthraj19 just so I can review with feedback before we merge
Closes #7

Implement the order list structure

---

src/main/java/sim/coffee/Beverage.java
src/main/java/sim/coffee/Food.java
src/main/java/sim/coffee/IllegalIDException.java
src/main/java/sim/coffee/MenuItem.java
src/main/java/sim/coffee/Merchandise.java
src/test/java/sim/coffee/IllegalIDExceptionTest.java

Fixed code redundancy in MenuItem subclasses, id check now moved back to the parent class.

Implement IllegalIDExceptionTest class and updates to MenuItem class

---

src/main/java/sim/coffee/OrderBasket.java
src/test/java/sim/coffee/OrderBasketTest.java

Added new tests for discounts with multiple pairings present in basket and this was failing.
Also took the opportunity to simplify discount 3.

Fix discount 2 when multiple pairs are present

---

src/main/java/sim/coffee/Order.java
src/main/java/sim/coffee/OrderBasket.java
src/main/java/sim/coffee/OrderList.java
src/test/java/sim/coffee/OrderBasketTest.java
src/test/java/sim/coffee/OrderListTest.java

fixes #37 bug where getTotalIncome() would return £168.xx instead of just income for the day.

Fix total income

---

src/test/java/sim/coffee/OrderListTest.java

OrderList test should be independent as possible from other classes so that they don't fail if the other class isn't working. The test logic is otherwise the same.

Remove test dependency on Menu

---

src/main/java/sim/coffee/BasketTableModel.java
src/main/java/sim/coffee/Order.java

What was causing the error message to sometimes appear when adding items to basket.
I also made it so the % column in the UI doesn't show decimals anymore since they aren't significant there.

Fix handling of repeating decimals for display

---

src/main/java/sim/coffee/BasketTableModel.java
src/main/java/sim/coffee/CustomerGUI.java
src/main/java/sim/coffee/OrderBasket.java

- Some minor clean up of the GUI and output report strings
- Added the dietary classes to the GUI as a list
If I have time later I may have a crack at improving the layout of everything in another PR
Closes #46

Clean up GUI and output strings

---

src/main/java/sim/coffee/OrderBasket.java

Just an optimisation refactor.
Closes #44

Use a StringBuilder to create the output report

---

src/main/java/sim/coffee/ControlsBeverage.java
src/main/java/sim/coffee/ControlsMerchandise.java
src/main/java/sim/coffee/CustomerGUI.java

When the permutation was set I forgot to pass the calculated price through to the order instantiation
Fixes #51

Fix permutation price not being applied

---

data/menu.csv
src/main/java/sim/coffee/Milk.java

Fix milk price

---

src/main/java/sim/coffee/Log.java
src/main/java/sim/coffee/Queue.java

LinkedList in the Queue class now holds a list of Order[] so some methods needed updating.
Log class implements the Singleton pattern. 
Fixes #60

Implement Log class & update Queue class

---

src/main/java/sim/coffee/Producer.java

Fixes 4 issues:
- The type of the array was wrong (raised by @LinaRietuma in today's stand-up meeting)
- I had accidentally inverted the logic for when the next customer is reached
- I had forgot to update the variable tracking the customer currently ordering
- An empty array is no longer produced for the 0th (non-existent) customer

Fix issues with arrays produced

---

src/main/java/sim/coffee/Kitchen.java
src/main/java/sim/coffee/KitchenGUI.java
src/main/java/sim/coffee/KitchenQueueGUI.java
src/main/java/sim/coffee/Logger.java
src/main/java/sim/coffee/Manager.java
src/main/java/sim/coffee/Observer.java
src/main/java/sim/coffee/QueueType.java
src/main/java/sim/coffee/Server.java
src/main/java/sim/coffee/ServerGUI.java
src/main/java/sim/coffee/SharedQueue.java
src/main/java/sim/coffee/SimulationGUI.java
src/main/java/sim/coffee/Subject.java

Think this might be ready to be merged in the main branch. 
For now the GUI has four sections -  customer queue (split in two - ordinary and priority queue), servers, kitchen queue and the kitchen. All sections are updating as the simulation runs (except for priority queue, will have to add it in once ready), I've also assumed that all of the controls will be added in in the next iteration so have left them out for now. There are still some issues with the GUI (doesn't close when all threads are finished, need to make kitchen queue scrollable etc) but before I add them to the issue tracker, wanted know your thoughts on the GUI and if there are any fundamental flaws that need changing.

Implement GUI 

---

src/main/java/sim/coffee/Kitchen.java
src/main/java/sim/coffee/KitchenQueueGUI.java
src/main/java/sim/coffee/SharedQueue.java
src/main/java/sim/coffee/SimulationGUI.java

StringBuilder from getQueue() in SharedQueue class has been moved to the respective update() methods.
Closes #80

Improve coherence of SharedQueue class

---

src/main/java/sim/coffee/KitchenGUI.java
src/main/java/sim/coffee/KitchenQueueGUI.java
src/main/java/sim/coffee/SimulationGUI.java

Make kitchen queue section in the GUI scrollable

---

pom.xml
src/main/java/sim/app/Manager.java
src/main/java/sim/app/Order.java
src/main/java/sim/app/OrderBasket.java
src/main/java/sim/app/OrderItem.java
src/main/java/sim/app/OrderList.java
src/main/java/sim/coffee/BasketTableModel.java
src/main/java/sim/coffee/CustomerGUI.java
src/main/java/sim/coffee/MenuItem.java
src/main/java/sim/model/Kitchen.java
src/main/java/sim/model/Logger.java
src/main/java/sim/model/Producer.java
src/main/java/sim/model/QueueType.java
src/main/java/sim/model/Server.java
src/main/java/sim/model/SharedQueue.java
src/main/java/sim/model/Subject.java
src/main/java/sim/view/KitchenGUI.java
src/main/java/sim/view/KitchenQueueGUI.java
src/main/java/sim/view/Observer.java
src/main/java/sim/view/ServerGUI.java
src/main/java/sim/view/SimulationGUI.java
src/test/java/sim/coffee/BasketTableModelTest.java
src/test/java/sim/coffee/IllegalIDExceptionTest.java
src/test/java/sim/coffee/MenuTableModelTest.java
src/test/java/sim/coffee/MenuTest.java
src/test/java/sim/coffee/OrderBasketTest.java
src/test/java/sim/coffee/OrderListTest.java
src/test/java/sim/coffee/OrderTest.java

As per the specification.
@LinaRietuma Requesting your review as you did most of the MVC work in iteration 2.
This seems to work fine, not sure if it will causes issues when building to a JAR file with Maven later.
I left the stage 1 classes in the `sim.coffee` package for now in case we want to use anything from there later (Order stuff in `sim.app` with `Manager` class as I think some of the code there is relevant). If not it can be stripped out at the end.
Closes #86

Structure MVC classes into appropriate packages

---

src/main/java/sim/app/Manager.java
src/main/java/sim/model/CoffeeShop.java
src/main/java/sim/model/Server.java
src/main/java/sim/model/Subject.java
src/main/java/sim/view/Observer.java
src/main/java/sim/view/ServerGUI.java
src/main/java/sim/view/SimulationGUI.java

- Seperate the model initalisation out of the GUI
- Instantiates all the staff and queues, etc.
- Ready for logic to take actions when shop closes (still needs the code to detect this, then should perform an update for the UI to present some kind of dialog message)
Closes #88

Introduce CoffeeShop class

---

src/main/java/sim/controller/SpeedController.java
src/main/java/sim/model/Server.java
src/main/java/sim/view/ServerGUI.java
src/main/java/sim/view/SimulationGUI.java

I've added a slider for each server (not quite sure if this closes #84 or we want more controls?) and a label which updates to reflect the newly selected speed (just to provide some form of feedback, otherwise it's not always very obvious that the processing speed of orders has changed).  
I went with instantiating the controller in the main GUI since the `SpeedController` takes both `ServerGUI` and `Server` objects as arguments (other options would require shuffling a bit more code around).

Implement serving speed controls

---

src/main/java/sim/model/CoffeeShop.java
src/main/java/sim/model/SharedQueue.java
src/main/java/sim/views/QueueGUI.java
src/main/java/sim/views/SimulationGUI.java

Reuse queue view and show priority queue

---

src/main/java/sim/views/KitchenGUI.java
src/main/java/sim/views/QueueGUI.java
src/main/java/sim/views/ServerGUI.java
src/main/java/sim/views/SimulationGUI.java

A message dialog pops up once the simulation ends.
Also, the misalignment of customer names and ordered items in the queue sections was bugging me so I've fixed that which means I had to change the font to a fixed-width one to get the String.format() to function correctly. For consistency's sake I updated the font in the rest of the sections as well but this can be removed if we think the different fonts between section boarders and the display is an issue. 
Closes #87

Add message dialog at the end if simulation

---

src/main/java/sim/model/Kitchen.java
src/main/java/sim/model/Server.java
src/main/java/sim/model/SharedQueue.java
src/main/java/sim/views/KitchenGUI.java
src/main/java/sim/views/ServerGUI.java

By making the while loop of the shared queue progress when the queue is
done any threads waiting to access the synchronised method won't get
stuck there in the code
As a result the method can possibly not return a value, so I introduced
the optional type (better practice than using null)
Fixes #98

Fix possibility for threads to wait indefinitely

---

.editorconfig

Should have taken care of this a while ago, but here now at least
Doesn't actually standardise all the existing file, but we can do that at the end of stage 2
Closes #11

Add EditorConfig file for consistency

---

src/main/java/sim/model/Producer.java

Fix order processing logic

---

src/main/java/sim/views/KitchenGUI.java
src/main/java/sim/views/ServerGUI.java

Update GUI formatting

---

src/main/java/sim/model/CoffeeShop.java
src/main/java/sim/model/Menu.java
src/main/java/sim/model/Producer.java
src/main/java/sim/model/ReportWriter.java

Flesh out report generated
